### ISSUE TITLE
Observability TODO

### ISSUE THREAD

**Issue by josevalim** [beam-telemetry/telemetry_metrics#45]
@arkgil @bryannaegele @GregMefford @tsloughter 

Here is a TODO of the changes we want to do on Telemetry Metrics based on the meeting:

  * [x] BN: Add an example of Telemetry.Metrics to Ecto and Phoenix
  * [x] BN: Move `telemetry_metrics_prometheus` and `telemetry_metrics_prometheus_core` to this organization (@bryannaegele you are already an admin)
  * [x] JV: Advertise the existing reporters in telemetry_metrics docs (and how to find more)
  * [x] JV: Standardize trace events (moved to #46)

**Comment by bryannaegele** [comment]
Examples are on the way for Ecto and Phoenix still. I should have PRs up next week.
